In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('data.csv', names=['method', 'b', 'h', 'seqlen', 'dim', 'n_dim', 'stages', 'iwo', 'pingpong', 'correct', 'ms', 'tflops', 'error', 'torch_ms'])

In [11]:
df_cute = df[(df['correct'] == True) & (~df['torch_ms'].isna())]

In [21]:
df_cute.loc[:, 'speedup'] = df_cute['torch_ms'] / df_cute['ms']
df_cute.loc[:, 'shape'] = df_cute['b'].astype(str) + ',' + df_cute['h'].astype(str) + ',' + df_cute['seqlen'].astype(str) + ',' + df_cute['dim'].astype(str)

In [26]:
idx = df_cute.groupby('shape')['speedup'].idxmax()
max_performers = df_cute.loc[idx]

In [40]:
max_performers[max_performers['dim'] == 128]

,method,b,h,seqlen,dim,n_dim,stages,iwo,pingpong,correct,ms,tflops,error,torch_ms,speedup,shape
233,cute,1,16,16384,128,128.0,2.0,False,True,True,3.270529,678.941511,NaN,3.279363,1.002701,"1,16,16384,128"
179,cute,1,8,16384,128,128.0,2.0,False,True,True,1.692462,655.996513,NaN,1.650747,0.975353,"1,8,16384,128"
197,cute,16,16,1024,128,128.0,2.0,False,True,True,0.240402,577.287409,NaN,0.230542,0.958983,"16,16,1024,128"
143,cute,16,8,1024,128,128.0,2.0,False,True,True,0.128611,539.536995,NaN,0.120022,0.933218,"16,8,1024,128"
224,cute,2,16,8192,128,128.0,2.0,False,True,True,1.662067,667.992934,NaN,1.634322,0.983307,"2,16,8192,128"
170,cute,2,8,8192,128,128.0,2.0,False,True,True,0.834138,665.507058,NaN,0.834672,1.000641,"2,8,8192,128"
188,cute,32,16,512,128,128.0,2.0,False,True,True,0.147302,471.075594,NaN,0.132557,0.899895,"32,16,512,128"
134,cute,32,8,512,128,128.0,2.0,False,True,True,0.081013,428.269821,NaN,0.072148,0.890577,"32,8,512,128"
215,cute,4,16,4096,128,128.0,2.0,False,True,True,0.850534,652.677886,NaN,0.837394,0.984551,"4,16,4096,128"
161,cute,4,8,4096,128,128.0,2.0,False,True,True,0.414310,669.938834,NaN,0.418567,1.010276,"4,8,4096,128"
206,cute,8,16,2048,128,128.0,2.0,False,True,True,0.431984,642.528759,NaN,0.435549,1.008253,"8,16,2048,128"
152,cute,8,8,2048,128,128.0,2.0,False,True,True,0.221413,626.796936,NaN,0.218021,0.984679,"8,8,2048,128"

In [34]:
idx = df_cute.groupby('shape')['speedup'].idxmin()
min_performers = df_cute.loc[idx]

In [37]:
min_performers[min_performers['dim'] == 128]

,method,b,h,seqlen,dim,n_dim,stages,iwo,pingpong,correct,ms,tflops,error,torch_ms,speedup,shape
234,cute,1,16,16384,128,128.0,2.0,True,False,True,3.705727,599.207200,NaN,3.279363,0.884945,"1,16,16384,128"
180,cute,1,8,16384,128,128.0,2.0,True,False,True,1.850424,599.996972,NaN,1.650747,0.892091,"1,8,16384,128"
199,cute,16,16,1024,128,128.0,2.0,True,True,True,0.287183,483.249015,NaN,0.230542,0.802767,"16,16,1024,128"
145,cute,16,8,1024,128,128.0,2.0,True,True,True,0.151340,458.508789,NaN,0.120022,0.793066,"16,8,1024,128"
225,cute,2,16,8192,128,128.0,2.0,True,False,True,1.833275,605.609552,NaN,1.634322,0.891476,"2,16,8192,128"
171,cute,2,8,8192,128,128.0,2.0,True,False,True,0.906633,612.292281,NaN,0.834672,0.920628,"2,8,8192,128"
190,cute,32,16,512,128,128.0,2.0,True,True,True,0.173424,400.121249,NaN,0.132557,0.764351,"32,16,512,128"
136,cute,32,8,512,128,128.0,2.0,True,True,True,0.093441,371.305036,NaN,0.072148,0.772120,"32,8,512,128"
216,cute,4,16,4096,128,128.0,2.0,True,False,True,0.908530,611.014200,NaN,0.837394,0.921703,"4,16,4096,128"
163,cute,4,8,4096,128,128.0,2.0,True,True,True,0.484093,573.365424,NaN,0.418567,0.864642,"4,8,4096,128"
208,cute,8,16,2048,128,128.0,2.0,True,True,True,0.496979,558.499507,NaN,0.435549,0.876395,"8,16,2048,128"
154,cute,8,8,2048,128,128.0,2.0,True,True,True,0.270751,512.578758,NaN,0.218021,0.805246,"8,8,2048,128"